### ISSUE TITLE
Swift Pro exception thrown 'device reports readiness to read but returned no data'

### ISSUE THREAD

**Issue by nick-jonas** [uArm-Developer/uArm-Python-SDK#11]
Whenever I start up my server that connects to my Swift Pro, I do this:

```
  # setup arm
  sys.path.append(os.path.join(os.path.dirname(__file__), '../..'))
  swift = SwiftAPI() # default by filters: {'hwid': 'USB VID:PID=2341:0042'}
  print('sleep 2 sec ...')
  sleep(2)
  print('device info: ')
  print(swift.get_device_info())
```

And the following happens:

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/Users/njonas/.pyenv/versions/3.6.1/lib/python3.6/site-packages/pyserial-3.4-py3.6.egg/serial/serialposix.py", line 501, in read
    'device reports readiness to read but returned no data '
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/njonas/.pyenv/versions/3.6.1/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/njonas/.pyenv/versions/3.6.1/lib/python3.6/site-packages/pyuf-1.3-py3.6.egg/uf/comm/serial_ascii.py", line 44, in run
    line = self.com.readline()
  File "/Users/njonas/.pyenv/versions/3.6.1/lib/python3.6/site-packages/pyserial-3.4-py3.6.egg/serial/serialposix.py", line 509, in read
    raise SerialException('read failed: {}'.format(e))
serial.serialutil.SerialException: read failed: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
```

And I also get this timeout:

```
cmd "#1 G0 Z40 F5000" timeout
```

It still works, but was wondering what this all meant and if there was a way to avoid it?

Thanks!

**Comment by dvanderelst** [comment]
Could you check whether the error is due to the get_info() function?

**Comment by nick-jonas** [comment]
@dvanderelst yes, I took that out and still get the error

**Comment by nick-jonas** [comment]
@dvanderelst Yea, same error with the get_info() function taken out

**Comment by nick-jonas** [comment]
Still getting this error.

And can someone tell me exactly what the "timeout" parameter does in set_position (not described in documentation), because I added timeout=0 and this disappeared:

```cmd "#1 G0 Z40 F5000" timeout```

**Comment by nick-jonas** [comment]
This issue was a mistake on my part, using a web server that was auto-reloading, causing the connection to the robot to freakout.
