### ISSUE TITLE
KeyError - Swift Pro

### ISSUE THREAD

**Issue by nick-jonas** [uArm-Developer/uArm-Python-SDK#13]
I'm trying to both start a web server and talk to the Swift Pro so on certain POST requests I can call 
 a series of set_position commands.

I don't really know what this error means, but I'm getting it from trying something pretty simple:

```
 * Running on http://localhost:8080/ (Press CTRL+C to quit)
 * Restarting with stat
setting up Swift...
Exception in thread Thread-14:
Traceback (most recent call last):
  File "/Users/njonas/.pyenv/versions/3.6.1/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/njonas/.pyenv/versions/3.6.1/lib/python3.6/threading.py", line 1182, in run
    self.function(*self.args, **self.kwargs)
  File "<my_project_path>/uf/comm/protocol_ascii.py", line 66, in timeout_cb
    self.delete() # TODO: avoid KeyError if the 'finish' called at same time
  File "<my_project_path>/uf/comm/protocol_ascii.py", line 53, in delete
    del self.owner.cmd_pend[self.cnt]
KeyError:
```

And this is what I'm doing to get this error:

    # setup arm
    print("setting up Swift...")
    sys.path.append(os.path.join(os.path.dirname(__file__), '../..'))
    swift = SwiftAPI() # default by filters: {'hwid': 'USB VID:PID=2341:0042'}

    sleep(2)

    if True != swift.set_position(z = RAISED_Z, relative = False, wait = True, speed = SPEED, timeout = 0):
      print("Set position failed!")

    swift.flush_cmd()
    sleep(1)

    if __name__ == '__main__':
        run_simple('localhost', 8080, app, use_reloader=True, use_debugger=True)

**Comment by nick-jonas** [comment]
The KeyError goes away when I change the timeout to >= 2.
